include: package:lint/analysis_options_package.yaml


analyzer:
  # exclude:
  #   - example/**
  #   - example/adaptative_theme_example/**
  #   - example/argo_example/**

linter:
  rules: 
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    sort_pub_dependencies: false
    constant_identifier_names: false
    avoid_positional_boolean_parameters: false
    prefer_initializing_formals: false
    use_setters_to_change_properties: false
    sort_unnamed_constructors_first: false
  