include: package:flutter_lints/flutter.yaml


analyzer:
  exclude:
    - example/**

linter:
  rules: 
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    sort_pub_dependencies: false
    constant_identifier_names: false
    avoid_positional_boolean_parameters: false
    prefer_initializing_formals: false
    use_setters_to_change_properties: false
    sort_unnamed_constructors_first: false
    no_leading_underscores_for_local_identifiers: false
  