name: argo
description: Responsive tools and widget for flutter apps.
version: 0.0.1
homepage: https://github.com/jamescardona11/argo

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.3