name: argo
description: Widgets and tools for make it easy to create responsive apps for mobile, tablet and web. You can find widget to handle visibility, orientation and handle diferent layout depend of screen. Additionally you can handle a responsive theme depends of screen.

version: 0.0.2
homepage: https://github.com/jamescardona11/argo

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.3